# Generated by Django 4.2.9 on 2024-04-04 14:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ordercast_country', '0001_initial'),
        ('ordercast_client', '0001_initial'),
        ('ordercast_product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('billing_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_countries', to='ordercast_country.country')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordercast_client.client')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='ordercast_product.product')),
                ('shipping_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_countries', to='ordercast_country.country')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
