# Generated by Django 4.2.9 on 2024-04-04 14:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('username', models.CharField(blank=True, max_length=64, verbose_name='Name')),
                ('email', models.EmailField(max_length=64, unique=True, verbose_name='Email')),
                ('is_approved', models.BooleanField(default=False)),
                ('tariff_name', models.CharField(choices=[('T0', 'Tariff 0'), ('T1', 'Tariff 1'), ('T2', 'Tariff 2'), ('T3', 'Tariff 3'), ('T4', 'Tariff 4'), ('T5', 'Tariff 5')], default='T0', max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
